Repository sujaltangde/JobLane, pull requests merged in 2024-05, with the labels that each got.

#35 Updated typos, duplicate FAQ and formatted address in Contact.jsx
  client/src/pages/Contact.jsx
Labels: gssoc, Level1

#30 Confirm Password feature added
  client/src/pages/Register.jsx
Labels: gssoc, Level1

#58 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, Level1

#55 Added colour to footer links
  client/src/components/Footer.jsx
Labels: good first issue, gssoc, Level1

#52 Navbar logo Fixed
  client/public/JoblaneLOGO.png
  client/src/components/Navbar.jsx
Labels: good first issue, gssoc, Level1

#64 added baseJobs in src/pages/Jobs.jsx
  client/src/pages/Jobs.jsx
Labels: bug, gssoc, Level2

#67 added validators to all routes for better error handling
  server/app.js
  server/controllers/JobControllers.js
  server/middlewares/error.js
  server/middlewares/validators.js
  server/package-lock.json
  server/package.json
  server/routes/AdminRoutes.js
  server/routes/ApplicationRoutes.js
  server/routes/JobRoutes.js
  server/routes/UserRoutes.js
Labels: enhancement, gssoc, Level2

#71 Docs: added issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: good first issue, gssoc, Level1

#74 fixes #72: setup details
  Learn.md
  server/config/config.sample.env
Labels: gssoc, Level1

#76 enhancement done : The card is now user responsive. fixes #57
  client/package-lock.json
  client/src/components/SaveJobCard.jsx
  client/src/pages/Home.jsx
Labels: gssoc, Level1

#80 Add 404-notfound page (fixes #69)
  client/src/App.jsx
  client/src/pages/NotFound.jsx
Labels: good first issue, gssoc, Level2

#81 Added Filter dropdown
  client/src/pages/Jobs.jsx
Labels: enhancement, gssoc, Level1

#84 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, Level1

#85 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc, Level1

#96 Feat: Added testimonials.
  client/package-lock.json
  client/package.json
  client/src/components/Testimonials/Testimonials.jsx
  client/src/components/Testimonials/testimonials.js
  client/src/pages/Home.jsx
Labels: enhancement, gssoc, Level2
