Repository sujaltangde/JobLane, pull requests merged in 2024-06, with the labels that each got.

#166 Bug Fix #156
  client/src/pages/JobDetails.jsx
Labels: enhancement, gssoc, Level1

#140 Footer Section Feature
  client/package-lock.json
  client/src/components/Accordion.jsx
  client/src/components/Card.jsx
  client/src/components/Footer.jsx
  client/src/pages/About.jsx
  client/src/pages/Contact.jsx
Labels: good first issue, gssoc, Level1

#108 Create autocomment-iss-close.yml
  .github/workflows/autocomment-iss-close.yml
Labels: enhancement, gssoc, Level2

#107 Create autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, Level2

#106 Create autocomment-pr-raise.yml
  .github/workflows/autocomment-pr-raise.yml
Labels: gssoc, Level1

#105 Create autocomment-issue.yml
  .github/workflows/autocomment-issue.yml
Labels: gssoc, Level2
